# Generated by Django 4.0.4 on 2022-07-16 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('nip', models.PositiveIntegerField()),
                ('devisi_pekerjaan', models.CharField(max_length=100)),
                ('alamat', models.CharField(max_length=50)),
                ('jenis_kelamin', models.CharField(max_length=100)),
            ],
        ),
    ]
